package:
    name: pymol 
    version: 1.9.0.0

source:
    svn_url: https://svn.code.sf.net/p/pymol/code/trunk
    svn_rev: r4178

requirements:
    build:
        - gcc
        - glew
        - libpng
        - freeglut
        - freetype
        - libxml2
        - numpy
        - python
    run:
        - libxml2
        - libpng
        - glew
        - freetype
        - freeglut
        - python
        - numpy
test:
  imports:
    - pymol
about:
    home: http://pymol.org/
    license: pymol oss license 
    summary: PyMOL is an OpenGL based molecular visualization system.
